package resources;
// Generated Jan 31, 2020 10:35:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer idaccount;
     private String name;
     private String contact;
     private String email;
     private String address;
     private String remarks;
     private Integer bank;
     private Integer customer;
     private Integer supplier;
     private Integer expences;
     private Integer employee;
     private Double debitBalance;
     private Double creditBalance;
     private Integer status;
     private Double creditLimit;
     private Double balance;
     private Set purchaseInvoiceOrders = new HashSet(0);
     private Set purchusInvoices = new HashSet(0);
     private Set holdReciptsForBankAccount = new HashSet(0);
     private Set invoiceReciptsForBankAccount = new HashSet(0);
     private Set invoiceReciptsForCustomer = new HashSet(0);
     private Set quotationInvoices = new HashSet(0);
     private Set otherTransesForBank = new HashSet(0);
     private Set holdReciptsForCustomer = new HashSet(0);
     private Set otherTransesForSupplier = new HashSet(0);
     private Set messesForEmployee = new HashSet(0);
     private Set chequeBooks = new HashSet(0);
     private Set messesForCustomer = new HashSet(0);
     private Set stockReturns = new HashSet(0);
     private Set customerBranches = new HashSet(0);
     private Set purchusInvoiceReciptsForSupplier = new HashSet(0);
     private Set saleInvoices = new HashSet(0);
     private Set customerTypeCustomers = new HashSet(0);
     private Set itemses = new HashSet(0);
     private Set holdInvoices = new HashSet(0);
     private Set purchusInvoiceReciptsForBank = new HashSet(0);

    public Account() {
    }

    public Account(String name, String contact, String email, String address, String remarks, Integer bank, Integer customer, Integer supplier, Integer expences, Integer employee, Double debitBalance, Double creditBalance, Integer status, Double creditLimit, Double balance, Set purchaseInvoiceOrders, Set purchusInvoices, Set holdReciptsForBankAccount, Set invoiceReciptsForBankAccount, Set invoiceReciptsForCustomer, Set quotationInvoices, Set otherTransesForBank, Set holdReciptsForCustomer, Set otherTransesForSupplier, Set messesForEmployee, Set chequeBooks, Set messesForCustomer, Set stockReturns, Set customerBranches, Set purchusInvoiceReciptsForSupplier, Set saleInvoices, Set customerTypeCustomers, Set itemses, Set holdInvoices, Set purchusInvoiceReciptsForBank) {
       this.name = name;
       this.contact = contact;
       this.email = email;
       this.address = address;
       this.remarks = remarks;
       this.bank = bank;
       this.customer = customer;
       this.supplier = supplier;
       this.expences = expences;
       this.employee = employee;
       this.debitBalance = debitBalance;
       this.creditBalance = creditBalance;
       this.status = status;
       this.creditLimit = creditLimit;
       this.balance = balance;
       this.purchaseInvoiceOrders = purchaseInvoiceOrders;
       this.purchusInvoices = purchusInvoices;
       this.holdReciptsForBankAccount = holdReciptsForBankAccount;
       this.invoiceReciptsForBankAccount = invoiceReciptsForBankAccount;
       this.invoiceReciptsForCustomer = invoiceReciptsForCustomer;
       this.quotationInvoices = quotationInvoices;
       this.otherTransesForBank = otherTransesForBank;
       this.holdReciptsForCustomer = holdReciptsForCustomer;
       this.otherTransesForSupplier = otherTransesForSupplier;
       this.messesForEmployee = messesForEmployee;
       this.chequeBooks = chequeBooks;
       this.messesForCustomer = messesForCustomer;
       this.stockReturns = stockReturns;
       this.customerBranches = customerBranches;
       this.purchusInvoiceReciptsForSupplier = purchusInvoiceReciptsForSupplier;
       this.saleInvoices = saleInvoices;
       this.customerTypeCustomers = customerTypeCustomers;
       this.itemses = itemses;
       this.holdInvoices = holdInvoices;
       this.purchusInvoiceReciptsForBank = purchusInvoiceReciptsForBank;
    }
   
    public Integer getIdaccount() {
        return this.idaccount;
    }
    
    public void setIdaccount(Integer idaccount) {
        this.idaccount = idaccount;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    public Integer getBank() {
        return this.bank;
    }
    
    public void setBank(Integer bank) {
        this.bank = bank;
    }
    public Integer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Integer customer) {
        this.customer = customer;
    }
    public Integer getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Integer supplier) {
        this.supplier = supplier;
    }
    public Integer getExpences() {
        return this.expences;
    }
    
    public void setExpences(Integer expences) {
        this.expences = expences;
    }
    public Integer getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Integer employee) {
        this.employee = employee;
    }
    public Double getDebitBalance() {
        return this.debitBalance;
    }
    
    public void setDebitBalance(Double debitBalance) {
        this.debitBalance = debitBalance;
    }
    public Double getCreditBalance() {
        return this.creditBalance;
    }
    
    public void setCreditBalance(Double creditBalance) {
        this.creditBalance = creditBalance;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Double getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(Double creditLimit) {
        this.creditLimit = creditLimit;
    }
    public Double getBalance() {
        return this.balance;
    }
    
    public void setBalance(Double balance) {
        this.balance = balance;
    }
    public Set getPurchaseInvoiceOrders() {
        return this.purchaseInvoiceOrders;
    }
    
    public void setPurchaseInvoiceOrders(Set purchaseInvoiceOrders) {
        this.purchaseInvoiceOrders = purchaseInvoiceOrders;
    }
    public Set getPurchusInvoices() {
        return this.purchusInvoices;
    }
    
    public void setPurchusInvoices(Set purchusInvoices) {
        this.purchusInvoices = purchusInvoices;
    }
    public Set getHoldReciptsForBankAccount() {
        return this.holdReciptsForBankAccount;
    }
    
    public void setHoldReciptsForBankAccount(Set holdReciptsForBankAccount) {
        this.holdReciptsForBankAccount = holdReciptsForBankAccount;
    }
    public Set getInvoiceReciptsForBankAccount() {
        return this.invoiceReciptsForBankAccount;
    }
    
    public void setInvoiceReciptsForBankAccount(Set invoiceReciptsForBankAccount) {
        this.invoiceReciptsForBankAccount = invoiceReciptsForBankAccount;
    }
    public Set getInvoiceReciptsForCustomer() {
        return this.invoiceReciptsForCustomer;
    }
    
    public void setInvoiceReciptsForCustomer(Set invoiceReciptsForCustomer) {
        this.invoiceReciptsForCustomer = invoiceReciptsForCustomer;
    }
    public Set getQuotationInvoices() {
        return this.quotationInvoices;
    }
    
    public void setQuotationInvoices(Set quotationInvoices) {
        this.quotationInvoices = quotationInvoices;
    }
    public Set getOtherTransesForBank() {
        return this.otherTransesForBank;
    }
    
    public void setOtherTransesForBank(Set otherTransesForBank) {
        this.otherTransesForBank = otherTransesForBank;
    }
    public Set getHoldReciptsForCustomer() {
        return this.holdReciptsForCustomer;
    }
    
    public void setHoldReciptsForCustomer(Set holdReciptsForCustomer) {
        this.holdReciptsForCustomer = holdReciptsForCustomer;
    }
    public Set getOtherTransesForSupplier() {
        return this.otherTransesForSupplier;
    }
    
    public void setOtherTransesForSupplier(Set otherTransesForSupplier) {
        this.otherTransesForSupplier = otherTransesForSupplier;
    }
    public Set getMessesForEmployee() {
        return this.messesForEmployee;
    }
    
    public void setMessesForEmployee(Set messesForEmployee) {
        this.messesForEmployee = messesForEmployee;
    }
    public Set getChequeBooks() {
        return this.chequeBooks;
    }
    
    public void setChequeBooks(Set chequeBooks) {
        this.chequeBooks = chequeBooks;
    }
    public Set getMessesForCustomer() {
        return this.messesForCustomer;
    }
    
    public void setMessesForCustomer(Set messesForCustomer) {
        this.messesForCustomer = messesForCustomer;
    }
    public Set getStockReturns() {
        return this.stockReturns;
    }
    
    public void setStockReturns(Set stockReturns) {
        this.stockReturns = stockReturns;
    }
    public Set getCustomerBranches() {
        return this.customerBranches;
    }
    
    public void setCustomerBranches(Set customerBranches) {
        this.customerBranches = customerBranches;
    }
    public Set getPurchusInvoiceReciptsForSupplier() {
        return this.purchusInvoiceReciptsForSupplier;
    }
    
    public void setPurchusInvoiceReciptsForSupplier(Set purchusInvoiceReciptsForSupplier) {
        this.purchusInvoiceReciptsForSupplier = purchusInvoiceReciptsForSupplier;
    }
    public Set getSaleInvoices() {
        return this.saleInvoices;
    }
    
    public void setSaleInvoices(Set saleInvoices) {
        this.saleInvoices = saleInvoices;
    }
    public Set getCustomerTypeCustomers() {
        return this.customerTypeCustomers;
    }
    
    public void setCustomerTypeCustomers(Set customerTypeCustomers) {
        this.customerTypeCustomers = customerTypeCustomers;
    }
    public Set getItemses() {
        return this.itemses;
    }
    
    public void setItemses(Set itemses) {
        this.itemses = itemses;
    }
    public Set getHoldInvoices() {
        return this.holdInvoices;
    }
    
    public void setHoldInvoices(Set holdInvoices) {
        this.holdInvoices = holdInvoices;
    }
    public Set getPurchusInvoiceReciptsForBank() {
        return this.purchusInvoiceReciptsForBank;
    }
    
    public void setPurchusInvoiceReciptsForBank(Set purchusInvoiceReciptsForBank) {
        this.purchusInvoiceReciptsForBank = purchusInvoiceReciptsForBank;
    }




}


