package resources;
// Generated Jan 31, 2020 10:35:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Items generated by hbm2java
 */
public class Items  implements java.io.Serializable {


     private Integer itemId;
     private Account account;
     private Brand brand;
     private Category category;
     private Type type;
     private String barcodeId;
     private String name;
     private String date;
     private Integer status;
     private Double he;
     private Double wi;
     private String image;
     private Set itemReorders = new HashSet(0);
     private Set typeCalcs = new HashSet(0);
     private Set stockTransfers = new HashSet(0);
     private Set salesReturnItemses = new HashSet(0);
     private Set itemThirds = new HashSet(0);
     private Set poOrderItemses = new HashSet(0);
     private Set purchusInvoiceItems = new HashSet(0);
     private Set holdInvoiceItems = new HashSet(0);
     private Set itemSubs = new HashSet(0);
     private Set saleInvoiceItems = new HashSet(0);
     private Set stocks = new HashSet(0);
     private Set quotationInvoiceItems = new HashSet(0);

    public Items() {
    }

	
    public Items(Account account, Brand brand, Category category, Type type, String barcodeId, String name) {
        this.account = account;
        this.brand = brand;
        this.category = category;
        this.type = type;
        this.barcodeId = barcodeId;
        this.name = name;
    }
    public Items(Account account, Brand brand, Category category, Type type, String barcodeId, String name, String date, Integer status, Double he, Double wi, String image, Set itemReorders, Set typeCalcs, Set stockTransfers, Set salesReturnItemses, Set itemThirds, Set poOrderItemses, Set purchusInvoiceItems, Set holdInvoiceItems, Set itemSubs, Set saleInvoiceItems, Set stocks, Set quotationInvoiceItems) {
       this.account = account;
       this.brand = brand;
       this.category = category;
       this.type = type;
       this.barcodeId = barcodeId;
       this.name = name;
       this.date = date;
       this.status = status;
       this.he = he;
       this.wi = wi;
       this.image = image;
       this.itemReorders = itemReorders;
       this.typeCalcs = typeCalcs;
       this.stockTransfers = stockTransfers;
       this.salesReturnItemses = salesReturnItemses;
       this.itemThirds = itemThirds;
       this.poOrderItemses = poOrderItemses;
       this.purchusInvoiceItems = purchusInvoiceItems;
       this.holdInvoiceItems = holdInvoiceItems;
       this.itemSubs = itemSubs;
       this.saleInvoiceItems = saleInvoiceItems;
       this.stocks = stocks;
       this.quotationInvoiceItems = quotationInvoiceItems;
    }
   
    public Integer getItemId() {
        return this.itemId;
    }
    
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public String getBarcodeId() {
        return this.barcodeId;
    }
    
    public void setBarcodeId(String barcodeId) {
        this.barcodeId = barcodeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Double getHe() {
        return this.he;
    }
    
    public void setHe(Double he) {
        this.he = he;
    }
    public Double getWi() {
        return this.wi;
    }
    
    public void setWi(Double wi) {
        this.wi = wi;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set getItemReorders() {
        return this.itemReorders;
    }
    
    public void setItemReorders(Set itemReorders) {
        this.itemReorders = itemReorders;
    }
    public Set getTypeCalcs() {
        return this.typeCalcs;
    }
    
    public void setTypeCalcs(Set typeCalcs) {
        this.typeCalcs = typeCalcs;
    }
    public Set getStockTransfers() {
        return this.stockTransfers;
    }
    
    public void setStockTransfers(Set stockTransfers) {
        this.stockTransfers = stockTransfers;
    }
    public Set getSalesReturnItemses() {
        return this.salesReturnItemses;
    }
    
    public void setSalesReturnItemses(Set salesReturnItemses) {
        this.salesReturnItemses = salesReturnItemses;
    }
    public Set getItemThirds() {
        return this.itemThirds;
    }
    
    public void setItemThirds(Set itemThirds) {
        this.itemThirds = itemThirds;
    }
    public Set getPoOrderItemses() {
        return this.poOrderItemses;
    }
    
    public void setPoOrderItemses(Set poOrderItemses) {
        this.poOrderItemses = poOrderItemses;
    }
    public Set getPurchusInvoiceItems() {
        return this.purchusInvoiceItems;
    }
    
    public void setPurchusInvoiceItems(Set purchusInvoiceItems) {
        this.purchusInvoiceItems = purchusInvoiceItems;
    }
    public Set getHoldInvoiceItems() {
        return this.holdInvoiceItems;
    }
    
    public void setHoldInvoiceItems(Set holdInvoiceItems) {
        this.holdInvoiceItems = holdInvoiceItems;
    }
    public Set getItemSubs() {
        return this.itemSubs;
    }
    
    public void setItemSubs(Set itemSubs) {
        this.itemSubs = itemSubs;
    }
    public Set getSaleInvoiceItems() {
        return this.saleInvoiceItems;
    }
    
    public void setSaleInvoiceItems(Set saleInvoiceItems) {
        this.saleInvoiceItems = saleInvoiceItems;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }
    public Set getQuotationInvoiceItems() {
        return this.quotationInvoiceItems;
    }
    
    public void setQuotationInvoiceItems(Set quotationInvoiceItems) {
        this.quotationInvoiceItems = quotationInvoiceItems;
    }




}


