package resources;
// Generated Jan 31, 2020 10:35:24 PM by Hibernate Tools 4.3.1



/**
 * ItemReorder generated by hbm2java
 */
public class ItemReorder  implements java.io.Serializable {


     private Integer iditemReorder;
     private Items items;
     private Double rol;
     private Double addIsEmpty;
     private Double addReOrderPassed;
     private Integer status;

    public ItemReorder() {
    }

	
    public ItemReorder(Items items) {
        this.items = items;
    }
    public ItemReorder(Items items, Double rol, Double addIsEmpty, Double addReOrderPassed, Integer status) {
       this.items = items;
       this.rol = rol;
       this.addIsEmpty = addIsEmpty;
       this.addReOrderPassed = addReOrderPassed;
       this.status = status;
    }
   
    public Integer getIditemReorder() {
        return this.iditemReorder;
    }
    
    public void setIditemReorder(Integer iditemReorder) {
        this.iditemReorder = iditemReorder;
    }
    public Items getItems() {
        return this.items;
    }
    
    public void setItems(Items items) {
        this.items = items;
    }
    public Double getRol() {
        return this.rol;
    }
    
    public void setRol(Double rol) {
        this.rol = rol;
    }
    public Double getAddIsEmpty() {
        return this.addIsEmpty;
    }
    
    public void setAddIsEmpty(Double addIsEmpty) {
        this.addIsEmpty = addIsEmpty;
    }
    public Double getAddReOrderPassed() {
        return this.addReOrderPassed;
    }
    
    public void setAddReOrderPassed(Double addReOrderPassed) {
        this.addReOrderPassed = addReOrderPassed;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


