package resources;
// Generated Jan 31, 2020 10:35:24 PM by Hibernate Tools 4.3.1



/**
 * PurchusInvoiceItem generated by hbm2java
 */
public class PurchusInvoiceItem  implements java.io.Serializable {


     private Integer idpurchusInvoiceItem;
     private Items items;
     private PurchusInvoice purchusInvoice;
     private Double qtt;
     private Double unitPrice;
     private Double descountRate;
     private Double descount;
     private Double total;
     private Double netTotal;
     private Integer status;

    public PurchusInvoiceItem() {
    }

	
    public PurchusInvoiceItem(Items items, PurchusInvoice purchusInvoice) {
        this.items = items;
        this.purchusInvoice = purchusInvoice;
    }
    public PurchusInvoiceItem(Items items, PurchusInvoice purchusInvoice, Double qtt, Double unitPrice, Double descountRate, Double descount, Double total, Double netTotal, Integer status) {
       this.items = items;
       this.purchusInvoice = purchusInvoice;
       this.qtt = qtt;
       this.unitPrice = unitPrice;
       this.descountRate = descountRate;
       this.descount = descount;
       this.total = total;
       this.netTotal = netTotal;
       this.status = status;
    }
   
    public Integer getIdpurchusInvoiceItem() {
        return this.idpurchusInvoiceItem;
    }
    
    public void setIdpurchusInvoiceItem(Integer idpurchusInvoiceItem) {
        this.idpurchusInvoiceItem = idpurchusInvoiceItem;
    }
    public Items getItems() {
        return this.items;
    }
    
    public void setItems(Items items) {
        this.items = items;
    }
    public PurchusInvoice getPurchusInvoice() {
        return this.purchusInvoice;
    }
    
    public void setPurchusInvoice(PurchusInvoice purchusInvoice) {
        this.purchusInvoice = purchusInvoice;
    }
    public Double getQtt() {
        return this.qtt;
    }
    
    public void setQtt(Double qtt) {
        this.qtt = qtt;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Double getDescountRate() {
        return this.descountRate;
    }
    
    public void setDescountRate(Double descountRate) {
        this.descountRate = descountRate;
    }
    public Double getDescount() {
        return this.descount;
    }
    
    public void setDescount(Double descount) {
        this.descount = descount;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Double getNetTotal() {
        return this.netTotal;
    }
    
    public void setNetTotal(Double netTotal) {
        this.netTotal = netTotal;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


