package resources;
// Generated Jan 31, 2020 10:35:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SubCategory generated by hbm2java
 */
public class SubCategory  implements java.io.Serializable {


     private Integer subcategoryId;
     private Category category;
     private String name;
     private Integer status;
     private Set itemSubs = new HashSet(0);
     private Set thirdCategories = new HashSet(0);

    public SubCategory() {
    }

	
    public SubCategory(Category category) {
        this.category = category;
    }
    public SubCategory(Category category, String name, Integer status, Set itemSubs, Set thirdCategories) {
       this.category = category;
       this.name = name;
       this.status = status;
       this.itemSubs = itemSubs;
       this.thirdCategories = thirdCategories;
    }
   
    public Integer getSubcategoryId() {
        return this.subcategoryId;
    }
    
    public void setSubcategoryId(Integer subcategoryId) {
        this.subcategoryId = subcategoryId;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getItemSubs() {
        return this.itemSubs;
    }
    
    public void setItemSubs(Set itemSubs) {
        this.itemSubs = itemSubs;
    }
    public Set getThirdCategories() {
        return this.thirdCategories;
    }
    
    public void setThirdCategories(Set thirdCategories) {
        this.thirdCategories = thirdCategories;
    }




}


