package resources;
// Generated Jan 31, 2020 10:35:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer status;
     private Set typeCalcsForType2 = new HashSet(0);
     private Set typeCalcsForType1 = new HashSet(0);
     private Set itemses = new HashSet(0);

    public Type() {
    }

    public Type(String name, Integer status, Set typeCalcsForType2, Set typeCalcsForType1, Set itemses) {
       this.name = name;
       this.status = status;
       this.typeCalcsForType2 = typeCalcsForType2;
       this.typeCalcsForType1 = typeCalcsForType1;
       this.itemses = itemses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getTypeCalcsForType2() {
        return this.typeCalcsForType2;
    }
    
    public void setTypeCalcsForType2(Set typeCalcsForType2) {
        this.typeCalcsForType2 = typeCalcsForType2;
    }
    public Set getTypeCalcsForType1() {
        return this.typeCalcsForType1;
    }
    
    public void setTypeCalcsForType1(Set typeCalcsForType1) {
        this.typeCalcsForType1 = typeCalcsForType1;
    }
    public Set getItemses() {
        return this.itemses;
    }
    
    public void setItemses(Set itemses) {
        this.itemses = itemses;
    }




}


